# WEEK1 线性代数

## 1. 范数总结

### 常用范数定义
- **范数（norm）**：用于衡量向量大小的函数，向量$x$的范数表示原点到点$x$的距离。

- $L^p$范数的定义为：$\left \| x \right \|_p = (\sum_i\left | x_i \right |^p)^\frac{1}{p}$

- 欧几里得范数（$L^2$范数）：$\left \|x\right \| = (\sum_i\left | x_i \right |^2)^\frac{1}{2}$

- 平方$L^2$范数：$x^\top x$

- 平方$L^2$范数比$L^2$范数更方便，但在原点附近增长缓慢，因此在需要区分零和非零但值很小的元素时，转而使用$L^1$范数。

- $L^1$范数：$\left \|x\right \|_1 = \sum_i\left | x_i \right |$

- 最大范数($L^\infty$)：$\left \|x\right \|_\infty = \max_i\left | x_i \right |$。用来表示向量中具有最大辐值的元素的绝对值。

- Frobenius范数：$\left \| A \right \|_F = \sqrt{\sum_{i,j} A^2_{i,j}}$。衡量矩阵大小。

### numpy 求范数
**numpy.linalg.norm(x, ord=None, axis=None)**

ord参数：


ord |norm for matrices |norm for vectors
--- |    ---       |---
None | Frobenius norm | 2-norm
‘fro’| Frobenius norm| –
inf |max(sum(abs(x), axis=1))|最大范数
-inf|min(sum(abs(x), axis=1))|min(abs(x))
0| – | sum(x != 0)
1 | max(sum(abs(x), axis=0))|L1范数
-1 |min(sum(abs(x), axis=0))|sum(abs(x)** ord)** (1./ord)

In [1]:
# numpy 求范数：np.linalg.norm
import numpy as np
from numpy import linalg as LA

arr = np.arange(9) - 4
mat = arr.reshape(3,3)

print('arr:')
print(arr)
print('')
print('mat:')
print(mat)
print('-------------------------------')
print('2-norm: ' + str(LA.norm(arr)))
print('max-norm: ' + str(LA.norm(arr,np.inf)))
print('1-norm: ' + str(LA.norm(arr,1)))
print('矩阵fro范数：' + str(LA.norm(mat,'fro')))

arr:
[-4 -3 -2 -1  0  1  2  3  4]

mat:
[[-4 -3 -2]
 [-1  0  1]
 [ 2  3  4]]
-------------------------------
2-norm: 7.745966692414834
max-norm: 4.0
1-norm: 20.0
矩阵fro范数：7.745966692414834
